### ISSUE TITLE
Tempo das mensagens

### ISSUE THREAD

**Issue by emtudo** [vuejs-br/vedobot#2]
Programar um tempo, para que a mensagem de "este cara é maior engraçado...." não repita uma em seguida da outra, não me pergunte que tempo seria bom, ou trocar a mensagem, ou ambos.

**Comment by vedovelli** [comment]
Na verdade eu não gosto destas mensagens automáticas. Elas entram no meio das conversas e atrapalham! Minha sugestão é deixar por um tempo e depois remove-las!

**Comment by IgorHalfeld** [comment]
Realmente essas mensagens automáticas atrapalham, foi legal no começo mas já deu xD
Elas foram removidas, só ficou uma que é a indicação do livro sobre Vue.

@vedovelli é só fazer o `git pull` e reiniciar o serviço no servidor para o bot parar de encher o saco kk

**Comment by vedovelli** [comment]
Está feito!
