### ISSUE TITLE
remover-post não remove

### ISSUE THREAD

**Issue by vedovelli** [vuejs-br/vedobot#4]

**Comment by IgorHalfeld** [comment]
Você esta tentando remover um post chamando o bot no private?
Só é possível remover um post pelo channel dos autores, já que só um autor pode fazer isso :D

**Comment by vedovelli** [comment]
Foi no canal blog!

**Comment by IgorHalfeld** [comment]
Não é porquê você tentou remover o post com data de 2016, mas registrou o post com data de 2015?

**Comment by vedovelli** [comment]
Sorry! =D
